
VM_RELEASE=4.0.4

VM_ISO_LINK="https://midnightbsd.org/ftp/MidnightBSD/releases/amd64/ISO-IMAGES/4.0.4/MidnightBSD-4.0.4--amd64-disc1.iso"
VM_OS_NAME="midnightbsd"
VM_OS_TYPE="freebsd14.0"
VM_SSH_PORT=2227


VM_ROOT_PASSWORD=midnightbsd

VM_SHUTDOWN_CMD="/sbin/shutdown -p now"

VM_INSTALL_CMD="mport install "

VM_RSYNC_PKG="rsync"
VM_SSHFS_PKG="fusefs-sshfs"

VM_PRE_INSTALL_PKGS="tree $VM_RSYNC_PKG || true"

VM_LOGIN_TAG="MidnightBSD"


VM_NIC=virtio

VM_OPTS="conf/midnightbsd-4.0.4.resp"

VM_VBOX="./vbox.sh"

VM_VBOX_LINK="https://raw.githubusercontent.com/anyvm-org/vbox/v1.2.4/vbox.sh"




